{ inputs, lib, config, pkgs, ... }: {
   home.packages = with pkgs; [ 
	firefox
	vim 
	htop
	virt-manager
	qemu
	docker
	obsidian
	waybar
	lua
	nodejs
	terminus-nerdfont
    terminus_font
    hyprpaper
	wofi
    wayland
    gimp
    rnix-lsp
    flameshot
    gnome.nautilus
    tor-browser-bundle-bin
    tor
    nodePackages.typescript
    nodePackages.typescript-language-server
    nodePackages.vscode-langservers-extracted
    nodePackages.nodemon
    sumneko-lua-language-server
    nodePackages.prettier
    postman
    postgresql
    mullvad-vpn
    proxychains
    weechat
    cacert
 ];
}
